name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * 1-5' # runs automatically at 12:00 pm (Monday to Friday)
  workflow_dispatch: 
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install --omit=optional
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: upload bug reports (to be downloaded from Github Actions UI)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bug-reports
        path: bug_report_*.xlsx
      
